  <tr><td>name</td><td><input type=text name='name' id='name' value='<%= theObject.getName() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>group</td><td><input type=text name='group' id='group' value='<%= theObject.getGroup() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>featuredVendorGroupId</td><td><input type=text name='featuredVendorGroupId' id='featuredVendorGroupId' value='<%= theObject.getFeaturedVendorGroupId() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>businessId</td><td><input type=text name='businessId' id='businessId' value='<%= theObject.getBusinessId() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>texasWeddingsBusinessId</td><td><input type=text name='texasWeddingsBusinessId' id='texasWeddingsBusinessId' value='<%= theObject.getTexasWeddingsBusinessId() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>texasWeddingsGroup</td><td><input type=text name='texasWeddingsGroup' id='texasWeddingsGroup' value='<%= theObject.getTexasWeddingsGroup() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>mobileDomain</td><td><input type=text name='mobileDomain' id='mobileDomain' value='<%= theObject.getMobileDomain() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>faceBook</td><td><input type=text name='faceBook' id='faceBook' value='<%= theObject.getFaceBook() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>twitter</td><td><input type=text name='twitter' id='twitter' value='<%= theObject.getTwitter() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>mySpace</td><td><input type=text name='mySpace' id='mySpace' value='<%= theObject.getMySpace() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>pinterest</td><td><input type=text name='pinterest' id='pinterest' value='<%= theObject.getPinterest() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>phone</td><td><input type=text name='phone' id='phone' value='<%= theObject.getPhone() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>email</td><td><input type=text name='email' id='email' value='<%= theObject.getEmail() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>virtualBookLink</td><td><input type=text name='virtualBookLink' id='virtualBookLink' value='<%= theObject.getVirtualBookLink() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>siteSpecificAttributeSubId</td><td><input type=text name='siteSpecificAttributeSubId' id='siteSpecificAttributeSubId' value='<%= theObject.getSiteSpecificAttributeSubId() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>blog</td><td><input type=text name='blog' id='blog' value='<%= theObject.getBlog() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>bridalExtravaganza</td><td><input type=text name='bridalExtravaganza' id='bridalExtravaganza' value='<%= theObject.getBridalExtravaganza() %>' size= maxchars=></td></tr></td></tr>
