CREATE TABLE EMAIL ( EMAIL.EMAILID integer, EMAIL.OWNERID integer, EMAIL.OWNERTYPE integer, EMAIL.SUBSCRIBE integer, EMAIL.EMAILADDRESS char(120), EMAIL.EMAILADDRESSTYPE integer, EMAIL.REFKEY char );
