  <tr><td>eventId</td><td><input type=text name='eventId' id='eventId' value='<%= theObject.getEventId() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>eventType</td><td><input type=text name='eventType' id='eventType' value='<%= theObject.getEventType() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>date</td><td><input type=text name='date' id='date' value='<%= theObject.getDate() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>ownerId</td><td><input type=text name='ownerId' id='ownerId' value='<%= theObject.getOwnerId() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>ownerType</td><td><input type=text name='ownerType' id='ownerType' value='<%= theObject.getOwnerType() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>description</td><td><input type=text name='description' id='description' value='<%= theObject.getDescription() %>' size=40 maxchars=254></td></tr></td></tr>
  <tr><td>comment</td><td><input type=text name='comment' id='comment' value='<%= theObject.getComment() %>' size=40 maxchars=254></td></tr></td></tr>
  <tr><td>originator</td><td><input type=text name='originator' id='originator' value='<%= theObject.getOriginator() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>reference</td><td><input type=text name='reference' id='reference' value='<%= theObject.getReference() %>' size= maxchars=></td></tr></td></tr>
