  <tr><td>status</td><td><input type=text name='status' id='status' value='<%= theObject.getStatus() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>coupleId</td><td><input type=text name='coupleId' id='coupleId' value='<%= theObject.getCoupleId() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>hisEmilAddress</td><td><input type=text name='hisEmilAddress' id='hisEmilAddress' value='<%= theObject.getHisEmilAddress() %>' size=40 maxchars=80></td></tr></td></tr>
  <tr><td>hisName</td><td><input type=text name='hisName' id='hisName' value='<%= theObject.getHisName() %>' size=40 maxchars=80></td></tr></td></tr>
  <tr><td>herEmailAddress</td><td><input type=text name='herEmailAddress' id='herEmailAddress' value='<%= theObject.getHerEmailAddress() %>' size=40 maxchars=80></td></tr></td></tr>
  <tr><td>herName</td><td><input type=text name='herName' id='herName' value='<%= theObject.getHerName() %>' size=40 maxchars=80></td></tr></td></tr>
  <tr><td>hisLastName</td><td><input type=text name='hisLastName' id='hisLastName' value='<%= theObject.getHisLastName() %>' size=30 maxchars=30></td></tr></td></tr>
  <tr><td>hisFirstName</td><td><input type=text name='hisFirstName' id='hisFirstName' value='<%= theObject.getHisFirstName() %>' size=30 maxchars=30></td></tr></td></tr>
  <tr><td>herLastName</td><td><input type=text name='herLastName' id='herLastName' value='<%= theObject.getHerLastName() %>' size=30 maxchars=30></td></tr></td></tr>
  <tr><td>herFirstName</td><td><input type=text name='herFirstName' id='herFirstName' value='<%= theObject.getHerFirstName() %>' size=30 maxchars=30></td></tr></td></tr>
  <tr><td>dateAdded</td><td><input type=text name='dateAdded' id='dateAdded' value='<%= theObject.getDateAdded() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>dateRemoved</td><td><input type=text name='dateRemoved' id='dateRemoved' value='<%= theObject.getDateRemoved() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>weddingDate</td><td><input type=text name='weddingDate' id='weddingDate' value='<%= theObject.getWeddingDate() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>hisAddressLine1</td><td><input type=text name='hisAddressLine1' id='hisAddressLine1' value='<%= theObject.getHisAddressLine1() %>' size=40 maxchars=50></td></tr></td></tr>
  <tr><td>hisAddressLine2</td><td><input type=text name='hisAddressLine2' id='hisAddressLine2' value='<%= theObject.getHisAddressLine2() %>' size=40 maxchars=50></td></tr></td></tr>
  <tr><td>hisAddressLine3</td><td><input type=text name='hisAddressLine3' id='hisAddressLine3' value='<%= theObject.getHisAddressLine3() %>' size=40 maxchars=50></td></tr></td></tr>
  <tr><td>herAddressLine1</td><td><input type=text name='herAddressLine1' id='herAddressLine1' value='<%= theObject.getHerAddressLine1() %>' size=40 maxchars=50></td></tr></td></tr>
  <tr><td>herAddressLine2</td><td><input type=text name='herAddressLine2' id='herAddressLine2' value='<%= theObject.getHerAddressLine2() %>' size=40 maxchars=50></td></tr></td></tr>
  <tr><td>herAddressLine3</td><td><input type=text name='herAddressLine3' id='herAddressLine3' value='<%= theObject.getHerAddressLine3() %>' size=40 maxchars=50></td></tr></td></tr>
  <tr><td>hisPhone</td><td><input type=text name='hisPhone' id='hisPhone' value='<%= theObject.getHisPhone() %>' size=20 maxchars=20></td></tr></td></tr>
  <tr><td>herPhone</td><td><input type=text name='herPhone' id='herPhone' value='<%= theObject.getHerPhone() %>' size=20 maxchars=20></td></tr></td></tr>
  <tr><td>notes</td><td><input type=text name='notes' id='notes' value='<%= theObject.getNotes() %>' size=40 maxchars=250></td></tr></td></tr>
  <tr><td>hisWorkPhone</td><td><input type=text name='hisWorkPhone' id='hisWorkPhone' value='<%= theObject.getHisWorkPhone() %>' size=20 maxchars=20></td></tr></td></tr>
  <tr><td>herWorkPhone</td><td><input type=text name='herWorkPhone' id='herWorkPhone' value='<%= theObject.getHerWorkPhone() %>' size=20 maxchars=20></td></tr></td></tr>
  <tr><td>hisBirthDate</td><td><input type=text name='hisBirthDate' id='hisBirthDate' value='<%= theObject.getHisBirthDate() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>herBirthDate</td><td><input type=text name='herBirthDate' id='herBirthDate' value='<%= theObject.getHerBirthDate() %>' size= maxchars=></td></tr></td></tr>
