  <tr><td>personId</td><td><input type=text name='personId' id='personId' value='<%= theObject.getPersonId() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>ownerId</td><td><input type=text name='ownerId' id='ownerId' value='<%= theObject.getOwnerId() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>ownerType</td><td><input type=text name='ownerType' id='ownerType' value='<%= theObject.getOwnerType() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>lastName</td><td><input type=text name='lastName' id='lastName' value='<%= theObject.getLastName() %>' size=40 maxchars=40></td></tr></td></tr>
  <tr><td>firstName</td><td><input type=text name='firstName' id='firstName' value='<%= theObject.getFirstName() %>' size=40 maxchars=40></td></tr></td></tr>
  <tr><td>middleName</td><td><input type=text name='middleName' id='middleName' value='<%= theObject.getMiddleName() %>' size=40 maxchars=40></td></tr></td></tr>
  <tr><td>title</td><td><input type=text name='title' id='title' value='<%= theObject.getTitle() %>' size=10 maxchars=10></td></tr></td></tr>
  <tr><td>nickName</td><td><input type=text name='nickName' id='nickName' value='<%= theObject.getNickName() %>' size=40 maxchars=40></td></tr></td></tr>
  <tr><td>suffix</td><td><input type=text name='suffix' id='suffix' value='<%= theObject.getSuffix() %>' size=10 maxchars=10></td></tr></td></tr>
  <tr><td>preferredName</td><td><input type=text name='preferredName' id='preferredName' value='<%= theObject.getPreferredName() %>' size=40 maxchars=100></td></tr></td></tr>
  <tr><td>sex</td><td><input type=text name='sex' id='sex' value='<%= theObject.getSex() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>age</td><td><input type=text name='age' id='age' value='<%= theObject.getAge() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>createDate</td><td><input type=text name='createDate' id='createDate' value='<%= theObject.getCreateDate() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>lastUpdate</td><td><input type=text name='lastUpdate' id='lastUpdate' value='<%= theObject.getLastUpdate() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>status</td><td><input type=text name='status' id='status' value='<%= theObject.getStatus() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>recordType</td><td><input type=text name='recordType' id='recordType' value='<%= theObject.getRecordType() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>comment</td><td><input type=text name='comment' id='comment' value='<%= theObject.getComment() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>url</td><td><input type=text name='url' id='url' value='<%= theObject.getUrl() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>siteDefEntityType</td><td><input type=text name='siteDefEntityType' id='siteDefEntityType' value='<%= theObject.getSiteDefEntityType() %>' size= maxchars=></td></tr></td></tr>
  <tr><td>birthDate</td><td><input type=text name='birthDate' id='birthDate' value='<%= theObject.getBirthDate() %>' size= maxchars=></td></tr></td></tr>
